### ISSUE TITLE
internal function problem with inheritance

### ISSUE THREAD

**Issue by haifenghuang** [crazywolf132/Mani#19]
Below code runs without problem:

```java
class Person {
    Person(first, last) {
        this.first = first;
        this.last = last;
    }

    normal() {
        say this.first + ", " + this.last;
    }

    internal reverse() {
        say this.last + " " + this.first;
    }

    both() {
        this.reverse();
        this.normal();
    }
}

class Man < Person {
    Man(first, last, age) {
        super.Person(first, last);
        this.age = age;
    }

    normal() {
        say this.first + ", " + this.last + ", " + this.age;
    }

    both() {
        this.reverse();
        this.normal();
    }
}

let m = Man("John", "Doe", 20);

m.normal();     // John, Doe, 20
m.both();       // Doe John ... John, Doe, 20
```

In subclass `Man`, the `both()` method calls `this.reverse()`, but `reverse()` is a internal method of class `Person`,  so it should not be used in subclass `Man`.

By the way, in subclass `Man`, the constructor is calling parent class `Person`'s constructor, but the syntax
is a little bit weird. It uses `super.Person(first, last)`, it should be better using `super(first, last)`.

**Comment by crazywolf132** [comment]
Thankyou for this. I will take a look now. :)

**Comment by crazywolf132** [comment]
As of the latest push, using `super.Person(first, last)` is now optional. You can just use `super(first, last)` as long as there is a constructor in the superclass.

**Comment by crazywolf132** [comment]
Feel free to come and join our community on Discord where we can discuss this more.

https://discord.gg/e37upmg

**Comment by crazywolf132** [comment]
@haifenghuang 
As of today, The above example works as expected.
