### ISSUE TITLE
Index out of bounds exception when combining lists into a map

### ISSUE THREAD

**Issue by Kalekdan** [crazywolf132/Mani#25]
If you create 2 lists (of the same size) and try and combine them into a map using map.combine(list1, list2); java throws and indexoutofbounds exception.
Will raise pr for fix shortly

**Comment by Kalekdan** [comment]
Also noticed when performing mymap.exists("keyname"); it would always return false, even if they key existed. Have updated and will include in same pr

**Comment by crazywolf132** [comment]
Thank you. Maybe if you want to split to a seperate pr, i will merge straight away

**Comment by Kalekdan** [comment]
Fixed in PR here (https://github.com/crazywolf132/Mani/pull/26)

**Comment by crazywolf132** [comment]
All tests pass. Closing issue.
