### ISSUE TITLE
Map test failures

### ISSUE THREAD

**Issue by Kalekdan** [crazywolf132/Mani#30]
**Describe the bug**
> Some tests are failing for map functions:
> - Copying of map seems to work (appears the same when say map) but .match does not recognise equality.
> - Creating several maps seems to throw an error (Will work on trying to find a consistent way to reproduce)

**To Reproduce**
> 1. Run tests

Code to reproduce:
> N/A

**Expected behavior**
> Expected to be able to create multiple maps without causing an error.

**Error**
> Look at test logs.

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Version [MOJAVE]

**Standard Library:**
Were you using a standard library?
> - [x] Yes
If yes, what libaries?
> Maps

If applicable, did you have internet connection?
> - [x] Yes

**Additional context**

**Comment by crazywolf132** [comment]
Update on status:

The problem with the several maps throwing an error, has been narrowed down to the delete task.
The task returns the actual map item rather than the class. This is what causes the errors.

**Comment by Kalekdan** [comment]
> Update on status:
> 
> The problem with the several maps throwing an error, has been narrowed down to the delete task.
> The task returns the actual map item rather than the class. This is what causes the errors.

I have looked into this again, the map creation issue issue was in fact the use of the variable name newMap in the tests. (not sure if this is an acceptable cause for error or not but I will update the tests to use a different variable name for now)
The copying map issue was due to an incorrect assignment when creating a the map

**Comment by crazywolf132** [comment]
Latest commits, fix error when reseting a map.

**Comment by Kalekdan** [comment]
This issue is complete. I will log a follow up bug report for the error when creating a map with name newMap

**Comment by crazywolf132** [comment]
@TheOnlyArtz Please fix your map search test

**Comment by crazywolf132** [comment]
@Kalekdan  Are we good to close this?

**Comment by Kalekdan** [comment]
The issue with maps called newMap still exists. This can be reproduced in the maps.mni test if the name of the myMap object is replaced to newMap. I'm not sure if this is an acceptable failure (whether we say the objects cannot be called newMap). Even if it is, it should probably throw a better error than:
 `Can only call functions and classes
[line 6]`
I will move this bug into a new issue though as it is not directly related to the tests.

I don't believe the map search test works yet, but since it is skipped for now, I suppose we can close this issue.
