### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Kalekdan** [crazywolf132/Mani#40]
**Is your feature request related to a problem? Please describe.**
>No existing guidance for anyone wishing to contribute and the procedures they should follow

**Describe the solution you'd like**
> A CONTRIBUTING.md file needs to be created to detail how someone can contribute and the standards/templates they should follow when doing so

**Describe alternatives you've considered**
>N/A

**Additional context**

**Comment by Kalekdan** [comment]
Taking this issue

**Comment by crazywolf132** [comment]
Merged to main branch.
