### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by crazywolf132** [crazywolf132/Mani#42]
**Is your feature request related to a problem? Please describe.**
> Namespaces would be ideal for this language, so then we can create a seperate on for each STDLIB, it also allows the user to have the same variable multiple times in different namespaces.

**Describe the solution you'd like**
> Create a hashmap of namespaces in the environment.

**Describe alternatives you've considered**
> Create a new data type.

**Additional context**

**Comment by crazywolf132** [comment]
@Kalekdan Maybe this is one you might like to do?

**Comment by Kalekdan** [comment]
> @Kalekdan Maybe this is one you might like to do?

Yeah I'll take this

**Comment by crazywolf132** [comment]
Maybe we could do something like creating a new Class type for the globals map. It could store data like the namespace, how many arguments the function has (if its a function) etc. Then we could potentially have function overloading too. 

This is just an idea, i look forward to seeing how you try to implement this feature.

**Comment by crazywolf132** [comment]
Namespaces is still currently underwork. So we need to keep this issue open. #61

**Comment by crazywolf132** [comment]
This got added with the latest pull request.
