### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by crazywolf132** [crazywolf132/Mani#43]
**Is your feature request related to a problem? Please describe.**
> Entities will act much like classes in the way you can create them, and they can store attributes etc. With one major difference. No constructor, and no functions. 
These can be used to store information (Any type, based on what the entity requires).

**Describe the solution you'd like**
> Create another class like the `ManiClass`, but call it `ManiEntity`. Then enable the declaration of attributes inside it.
We could then create a new way of calling them.

```JS
entity Foo {
    let bar;
    let baz;
}

let f = Foo(bar = 12; baz = "something");          // First example...
let ff = Foo(baz = "something"; bar = 12);         // Order does not matter.
```
> As we can see, it allows us to define what the variables inside the entity result in.

**Describe alternatives you've considered**
> Extend the regular `ManiClass` to allow the declaration of attributes outside the constructor.

**Additional context**

**Comment by crazywolf132** [comment]
@Kalekdan If your looking for another task. Maybe you could do this. 

Even if u maybe made something like a map, but the key will be an auto-increment from 0. Or it can be set....

**Comment by Kalekdan** [comment]
@crazywolf132 I'll take a look

**Comment by crazywolf132** [comment]
@Kalekdan how's this one going?

**Comment by Kalekdan** [comment]
@crazywolf132 Haven't gotten round to looking at this one yet, I'll make this my next priority

**Comment by crazywolf132** [comment]
@Kalekdan Any news?

**Comment by Kalekdan** [comment]
I had a quick look but I think I'm a bit over my head with most of this 😂 I might have to take a step back

**Comment by crazywolf132** [comment]
Thats ok, maybe want to take an easier task?

**Comment by Kalekdan** [comment]
Sure, I'd like to stay involved if you'll still have me! I'll take a look through the issues and pick one I might be able to tackle.
