### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by crazywolf132** [crazywolf132/Mani#44]
**Is your feature request related to a problem? Please describe.**
> What if we made a compiler? I have already started an attempt on my own GitHub of a similar thing, but what if we could incorporate something into here?

**Describe the solution you'd like**
> We could do it one of 2 ways. We could either convert everything to Java-byte code (Lots of work), or we could create a system to jerry rig it all into a JAR where Máni is a library. This library then reads the code from the resources directory and runs it. This could be a duct-tape solution that might actually work.

> We could also set up something in gradle to do this for us. (Move the Máni files and built library to a jar.

**Describe alternatives you've considered**
> As i said, we could also just try to convert everything to JAVA-byte code, but that will be heaps of work.

**Additional context**
> Here is the link to the repo i have already started this in.
https://github.com/crazywolf132/Mani-Compiler
> It would be good if we could actually have it all in the one repo rather than 2.

**Comment by crazywolf132** [comment]
@Kalekdan If you are stuck on your other task. Maybe you could work on this one instead.

It is a slightly easier task, as i have already done a fair bit on it.

https://github.com/crazywolf132/Mani-Compiler

It just needs to be updated to the latest version of mani (or even incorporated into this project with gradle). As well as look for a `main` function, after it reads in all of the code. Then execute it.

**Comment by Kalekdan** [comment]
Yeah, I'll take a look. Thanks

**Comment by crazywolf132** [comment]
@Kalekdan Finished this. It is merged and added.

Docs need to be added about it, and how to use it.
