### ISSUE TITLE
Graphics implementation.

### ISSUE THREAD

**Issue by crazywolf132** [crazywolf132/Mani#5]
**Is your feature request related to a problem? Please describe.**
> No

**Describe the solution you'd like**
> A graphics library called `Screens`, much like Java's swing. Here is an example.

~~~ JS
# "screens";

let view = Screen(250, 480, "Screen title");  // height, width, title

view.show(); // Displayed the window.

view.addButton("test button"); // Adds a button to the view instance.
~~~

**Describe alternatives you've considered**
> All these features are built straight into the core code. No library needed.

**Additional context**

**Comment by Beyarz** [comment]
Great idea!

**Comment by crazywolf132** [comment]
Recent commit 59b0b96e81de8d092a5273bbe7fbbbc82685e787, the Screens library was added.

It doesn't exactly match the above syntax, instead it matches this...

```moon
import("screens");

let view = Screen("Screen title"); // The title of the frame.

view.hide(); // Hides the window.

view.show(); // Displays the window.

view.addBasicBtn("Button Name"); // Adds a button to the frame. Used button text.
view.addBtn("Button Title", 0, 0, 100, 100); // Adds button. Title, x, y, width, height
```

**Comment by crazywolf132** [comment]
Should add this to the docs. #15 

Will close this issue, once that is complete.

**Comment by crazywolf132** [comment]
This is being closed as it is finished.
