### ISSUE TITLE
Add "break" keyword to escape loops

### ISSUE THREAD

**Issue by Kalekdan** [crazywolf132/Mani#67]
**Is your feature request related to a problem? Please describe.**
Would be useful to have the ability to escape a loop without having to wait for it to complete (for example if a condition is met)

**Describe the solution you'd like**
Something like the following should be possible:
~~~JS
let max = 5;
for (let i = 0; i <= 10; i++) {
    if (i == max) { break; }
}
~~~

**Describe alternatives you've considered**

**Additional context**

**Comment by crazywolf132** [comment]
Already exists.
~~~JS
>> let max = 5;
>> for (let i = 0; i <= 10; i++){ say i; if (i == 2) {  break; } }
0
1
2
>> 
~~~
