### ISSUE TITLE
Map naming 'newMap' error

### ISSUE THREAD

**Issue by Kalekdan** [crazywolf132/Mani#68]
**Describe the bug**
> Naming a map newMap throws an error when trying to create another map afterwards

**To Reproduce**
> 1. Copy the code provided below into a Máni script
> 2. Run the script
> 3. Observe the error thrown

Code to reproduce:
~~~JS
# "maps";

let newMap = Map();
let secondMap = Map();
~~~

**Expected behaviour**
> Second map should be created with no error.

**Error**
If applicable, please provide the full error.
~~~
Can only call functions and classes
[line 6]
~~~

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Version: 10

**Standard Library:**
Were you using a standard library?
> - [x] Yes

If yes, what libaries?
 - maps

If applicable, did you have internet connection?
> - [x] Yes

**Additional context**

**Comment by crazywolf132** [comment]
Updated message

**Comment by Kalekdan** [comment]
I believe this is happening due to the line in ```stdlib\maps.mni``` in the constructor ```this.map = newMap()```. It is trying to access the user created map object as a function when it exists with the name newMap. I imagine this will be fixed with the indroduction of namespaces #42 so it is not a high priority issue for now.

**Comment by crazywolf132** [comment]
Yeah, hopefully we can fix this with namespaces. We could also remove a few of the lines from each of the standard libraries as they were created before the introduction of the `addons` system #22

**Comment by crazywolf132** [comment]
fixed
